import { InpMonitor } from './inp-monitor'
// import { InpMonitor as VercelInpMonitor } from './vercel/inp-monitor'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <InpMonitor />
        {/* <VercelInpMonitor /> */}
        {children}
      </body>
    </html>
  )
}
